language: node_js
node_js: '6.3'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bash .travis/prepare.sh
sudo: required
script:
  - make
  - make tests
dist: trusty
deploy:
  - provider: script
    script: bash .travis/upload.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    file: "/tmp/os-loader-builddir/IMAGE/output/image.iso"
    api-key:
      secure: hk4WmwKTj1H9LEgdZYFmru24piTgbXjVTHWUZPyyQ5MVDJHl44yOFOQUolBHhR/AIqgV8UMWcqIRzGGvelMiwpm6jyju8Ia+538jkCAjb3DvH4T2ErhMGdy3kY60Sp9BCBp5hgY2awnFLvNNZppoNabbW/DmwJ3A6WKKGGFiGAHY82uR4GypHr/S6h8ZzAhd0YtPlVpQgI1wjbv40icTtqp1BXyKxuhgCVzQ4K/8gFXxpU4x6VF5w9EmIBd0Q0lx8sH01M7KD6UJI5BfJRT6iA/M8o81Fz1xC2YnoiGpTxqWjYuYWq15Vy7sV5ng4GR6w33X+r8pYcyg+c4Na2EkLLOuLowVmLWHPdQZYWfeNc5QLad2pGpyiwj+SpnwDNCU9N4bAzZ/pQ3Ht47X+No7eaiSf8CT2knpQgZOvf7yQkpeJxIAP3V2xi/Trfc24qrnbsR2JZ4A39vDpkSyEsDqnIsLmZeLlmMj6+DQNhm2EqF7BOce+c5dzA5eplA5LXZZtY3LE9Kj/5LdrMmguyNHPFnnWYziw5+02LbYcbjD506B6ycljwNXmapb+e8cZ0Le07PVot2SBApQseJo6LHy8qQKFVgOJk5zDCaQLCHPT/5YJpzCeJVkTiFrMm+rET/n+FXQuj7tn4bDxX+GeTCq//0isfNoupOUfDttmlGLEA8=
    skip_cleanup: true
    on:
      tags: true
addons:
  apt:
    packages:
    - genisoimage
    - squashfs-tools
    - tar
    - cpio
    - gzip
    - make
    - debootstrap
    - schroot
    - coreutils
    - curl
    - debhelper
    - dpkg-dev
    - openssl
    - git
env:
  global:
    secure: R9AFwuA92Y7KcaaY3eFISztKxB5e5ZK1aEKVekAzblB7LxT9C1KLD/r4rcjMpPfIr9icUo4Cw9JU3DLa75JjxEGfudpAZwa/G1y0TGM/CmfWVQ6lRHWyjOvdt/vQBYwc3gyotHJOMU8mGk8jLVrtPePuuE3joXYObo/BdZ9Ut6vwScbjgfCLqCtoaE1RR04Pxd7+BKcJf/Qro4TgXztfvI0og71OvwgORAPvttyyMjVpQDaL7Bx0KflbdU0KvftPmIVxqljY50toqWRQvJS6ZmjyeKCzO56UPloz+uny2aRjgxJJi22wDU7BxOACaoFuZ2It+UyI8leaezcRaHy13XiuQkNprQFdOhdZUgi7tYYgu4B2CI/pJOi5qz5nyELlF4F7yyszz15EbjNY/c7I0DQXorCG6LHH+kgNEWybzuLCXeXkatgh5eUW/Ki+FSjKno4cNQLwX17sZbT6lBSTob+dOkg6RVyLwhFLHww5dyfV11rF25ZH0pZBj7G7CRM2tsUOD1zjdvMa/zki4olbrIAWgPj31n8dg+XhoUBECk4ChcncNn+/qrKzom/WWTVfd61SKaMo/pYrhNQPIjNljQZyOVilH9JUsPsCvFgNAmtWDeC9+8hABnA1Eq+VMWM3CdNq9xKrLIZqJKaEY4hNHfIAEZTB5DiK3OzEtXom7zc=
