language: node_js
node_js: "6.1"
before_script: bash .travis/prepare.sh
sudo: required
script: make
dist: trusty
after_script: bash .travis/upload.sh
#env:
#  - CXX=g++-4.8
addons:
  apt:
#    sources:
#      - ubuntu-toolchain-r-test
    packages:
#      - g++-4.8
      - genisoimage
      - squashfs-tools
      - tar
      - cpio
      - gzip
      - make
      - debootstrap
      - schroot
      - coreutils
      - curl
      - debhelper
      - dpkg-dev
      - openssl
      - git
#      - isolinux N/A
