name: os-loader-server
version: 0.0.1
summary: OS Loader Image Server
description: Allows you to serve a repo with links to images, patches and more
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
  os-loader-server:
    command: os-loader-server
    plugs:
      - network
      - network-bind

parts:
  main:
    plugin: make
    source: .
#    stage-packages:
#      nodejs
